---
# https://github.com/TheSpad/docker-get_iplayer
# docker exec -it get_iplayer /app/get_iplayer/get_iplayer "hey duggee"
version: "3.8"
services:
  get_iplayer:
    image: edgd1er/get_iplayer
    container_name: get_iplayer
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - VERSION=3.35
        - APP_VERSION=3.35
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Paris
      - INCLUDERADIO= #optional
      - BASEURL= #optional
      - ENABLEIMPORT= #optional
      - PROXY=NORDLYNX:8888
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 1935:1935
    restart: unless-stopped
    networks :
      - nordlynx-proxy_default

networks:
  nordlynx-proxy_default:
    external: true