#!/usr/bin/with-contenv bash
OPTIONS=""
if [ -n "$PROXY" ]; then
  export HTTP_PROXY=http://$PROXY
fi

if [ -n "$BASEURL" ]; then
  OPTIONS=" -b $BASEURL"
fi

echo OPTIONS: $OPTIONS
exec 2>&1 \
  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 1935" \
  s6-setuidgid abc /app/get_iplayer/get_iplayer.cgi -p 1935 $OPTIONS --getiplayer /app/get_iplayer/get_iplayer;
