name: Check for base image updates
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  call-workflow:
    uses: thespad/actions/.github/workflows/check-baseimage-update.yml@v5
    with:
      repo_owner: ${{ github.repository_owner }}
      baseimage: "alpine"
      basebranch: "3.15"
      app_name: "get_iplayer"
    secrets:
      repo_scoped_token: ${{ secrets.repo_scoped_token }}
